import 'package:test/test.dart';
import 'package:matrix_dart_generated_client/openapi.dart';

// tests for RequestTokenTo3PIDMSISDNRequest
void main() {
  final instance = RequestTokenTo3PIDMSISDNRequestBuilder();
  // TODO add properties to the builder and call build()

  group(RequestTokenTo3PIDMSISDNRequest, () {
    // A unique string generated by the client, and used to identify the validation attempt. It must be a string consisting of the characters `[0-9a-zA-Z.=_-]`. Its length must not exceed 255 characters and it must not be empty. 
    // String clientSecret
    test('to test the property `clientSecret`', () async {
      // TODO
    });

    // The two-letter uppercase ISO-3166-1 alpha-2 country code that the number in `phone_number` should be parsed as if it were dialled from.
    // String country
    test('to test the property `country`', () async {
      // TODO
    });

    // Optional. When the validation is completed, the identity server will redirect the user to this URL. This option is ignored when submitting 3PID validation information through a POST request.
    // String nextLink
    test('to test the property `nextLink`', () async {
      // TODO
    });

    // The phone number to validate.
    // String phoneNumber
    test('to test the property `phoneNumber`', () async {
      // TODO
    });

    // The server will only send an SMS if the `send_attempt` is a number greater than the most recent one which it has seen, scoped to that `country` + `phone_number` + `client_secret` triple. This is to avoid repeatedly sending the same SMS in the case of request retries between the POSTing user and the identity server. The client should increment this value if they desire a new SMS (e.g. a reminder) to be sent.
    // int sendAttempt
    test('to test the property `sendAttempt`', () async {
      // TODO
    });

    // An access token previously registered with the identity server. Servers can treat this as optional to distinguish between r0.5-compatible clients and this specification version.  Required if an `id_server` is supplied.
    // String idAccessToken
    test('to test the property `idAccessToken`', () async {
      // TODO
    });

    // The hostname of the identity server to communicate with. May optionally include a port. This parameter is ignored when the homeserver handles 3PID verification.  This parameter is deprecated with a plan to be removed in a future specification version for `/account/password` and `/register` requests.
    // String idServer
    test('to test the property `idServer`', () async {
      // TODO
    });

  });
}
