import 'package:test/test.dart';
import 'package:matrix_dart_generated_client/openapi.dart';

// tests for UnsignedData
void main() {
  final instance = UnsignedDataBuilder();
  // TODO add properties to the builder and call build()

  group(UnsignedData, () {
    // The time in milliseconds that has elapsed since the event was sent. This field is generated by the local homeserver, and may be incorrect if the local time on at least one of the two servers is out of sync, which can cause the age to either be negative or greater than it actually is.
    // int age
    test('to test the property `age`', () async {
      // TODO
    });

    // The room membership of the user making the request, at the time of the event.  This property is the value of the `membership` property of the requesting user's [`m.room.member`](https://spec.matrix.org/v1.13/client-server-api#mroommember) state at the point of the event, including any changes caused by the event. If the user had yet to join the room at the time of the event (i.e, they have no `m.room.member` state), this property is set to `leave`.  Homeservers SHOULD populate this property wherever practical, but they MAY omit it if necessary (for example, if calculating the value is expensive, servers might choose to only implement it in encrypted rooms). The property is *not* normally populated in events pushed to application services via the application service transaction API (where there is no clear definition of \"requesting user\"). 
    // String membership
    test('to test the property `membership`', () async {
      // TODO
    });

    // The previous `content` for this event. This field is generated by the local homeserver, and is only returned if the event is a state event, and the client has permission to see the previous content. 
    // JsonObject prevContent
    test('to test the property `prevContent`', () async {
      // TODO
    });

    // The event that redacted this event, if any.
    // JsonObject redactedBecause
    test('to test the property `redactedBecause`', () async {
      // TODO
    });

    // The client-supplied [transaction ID](https://spec.matrix.org/v1.13/client-server-api/#transaction-identifiers), for example, provided via `PUT /_matrix/client/v3/rooms/{roomId}/send/{eventType}/{txnId}`, if the client being given the event is the same one which sent it. 
    // String transactionId
    test('to test the property `transactionId`', () async {
      // TODO
    });

  });
}
